version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/aws_code_pipeline
permissions:
  - object: /home/ubuntu/aws_code_pipeline
    owner: root
    group: root
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: root
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: root
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: root
      - location: scripts/gunicorn.sh
        timeout: 300
        runas: root
      - location: scripts/nginx.sh
        timeout: 300
        runas: root
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: root
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: root
  
  
